### ISSUE TITLE
plio viewhelpers aren't resolved in Windows environment

### ISSUE THREAD

**Issue by vaxul** [NamelessCoder/patternlab-fluid-patternengine#3]
Hi,

first of all, thank you for this project. 

I tried it for the first time and test the out of the box setup from https://github.com/NamelessCoder/patternlab-fluid-edition

My setup is:
- Windows 10 
- php-7.2.1-nts-Win32-VC15-x64 from CLI
- latest patternlab-fluid-edition

Currently the plio-viewhelper in source/_patterns/02-organisms/00-global/01-someorganism.fluid isn't resolved properly.
I got the message: `ViewHelper plio:special could not be resolved (0) ` in the rendered output.

So I digged into the code and found this line of code which doesn't work in my environment:
https://github.com/NamelessCoder/patternlab-fluid-patternengine/blob/fc12219f1ede0efe3af9d63f9b8db62cffe99724/src/Resolving/PatternLabViewHelperResolver.php#L30-L34

The cause is, that `PHP_EOL` has the value of `\r\n` (Windows) while in the targeted file has only `\n` in it.

See:
![image](https://user-images.githubusercontent.com/3798226/55940621-c7b98f80-5c40-11e9-993f-65f00de2b9a0.png)

Note: The files might be handled differently in other IDEs.

I thought about a less environment agnostic solution. The best I came up with is:
```php
$namespacePosition = strpos($classFileContents, "\n" . 'namespace ');
```
Which would work for `\r\n` and `\n`. Would you accept this as pull request and release a new version with this "patch"?

Best regards

**Comment by NamelessCoder** [comment]
Hi @vaxul,

A change to match `"\n"` sounds reasonable. Feel free to create PR!
